name: .NET Build Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore SampleRestApi/SampleRestApi/SampleRestApi.csproj

    - name: Build
      run: dotnet build SampleRestApi/SampleRestApi/SampleRestApi.csproj --no-restore

    - name: Test
      run: dotnet test SampleRestApi/SampleRestApi/SampleRestApi.csproj --no-build
